### PR TITLE
Students

### PR DESCRIPTION
**Pull request by rajenderreddi**

### CODE REVIEW

**Comment by hridayraag** [comment]
[Devops_assignment4.docx](https://github.com/Wiselin52/DevOps-CTU/files/1137441/Devops_assignment4.docx)

**Comment by hridayraag** [comment]
[Devops_assignment5.docx](https://github.com/Wiselin52/DevOps-CTU/files/1178563/Devops_assignment5.docx)

**Comment by shaik039** [comment]
[Ubuntu_Ass1.docx](https://github.com/Wiselin52/DevOps-CTU/files/1203584/Ubuntu_Ass1.docx)

**Comment by shaik039** [comment]
[Maven_Assingment3.docx](https://github.com/Wiselin52/DevOps-CTU/files/1203587/Maven_Assingment3.docx)

**Comment by shaik039** [comment]
[Jenkins_Ass2.docx](https://github.com/Wiselin52/DevOps-CTU/files/1203589/Jenkins_Ass2.docx)

**Pull request closed without merging**
